import { readFileSync } from 'node:fs';
import { describe, expect, it, vi } from 'vitest';
import { loadRigClip } from './clip';
import { createClipProjection, projectClipFrame, resetClipProjection, roundHalfAway } from './project';
import { loadRigSet } from './manifest';
import { createPlaceholderRigManifest } from './placeholder';

const walk = loadRigClip(JSON.parse(readFileSync(
  new URL('../../../../assets/default/rig/clips/clip_walk.json', import.meta.url), 'utf8',
)));
const sword = loadRigClip(JSON.parse(readFileSync(
  new URL('../../../../assets/default/rig/clips/clip_sword_attack.json', import.meta.url), 'utf8',
)));
const chosen = [0, 7, 14, 21, 29, 36, 43, 50] as const;
// Generated by tools/rig/clips/clip_metrics.py: pelvis-relative neck/head/wrist_R/ankle_L at 128 ppm.
const golden = [
  [0, 4,72,5,83,-36,16,13,-100], [45,9,72,15,83,4,16,34,-100], [90,10,72,17,83,42,16,34,-100], [135,4,72,9,83,56,16,14,-100],
  [180,-4,72,-5,83,36,16,-13,-100], [225,-9,72,-15,83,-4,16,-34,-100], [270,-10,72,-17,83,-42,16,-34,-100], [315,-4,72,-9,83,-56,16,-14,-100],
  [0,2,72,3,82,-37,13,10,-101], [45,10,72,16,82,0,13,14,-101], [90,11,72,19,82,36,13,11,-101], [135,6,72,11,82,51,13,1,-101],
  [180,-2,72,-3,82,37,13,-10,-101], [225,-10,72,-16,82,0,13,-14,-101], [270,-11,72,-19,82,-36,13,-11,-101], [315,-6,72,-11,82,-51,13,-1,-101],
  [0,-1,72,-1,82,-37,7,7,-104], [45,8,72,13,82,-16,7,-3,-104], [90,11,72,19,82,14,7,-12,-104], [135,8,72,14,82,36,7,-13,-104],
  [180,1,72,1,82,37,7,-7,-104], [225,-8,72,-13,82,16,7,3,-104], [270,-11,72,-19,82,-14,7,12,-104], [315,-8,72,-14,82,-36,7,13,-104],
  [0,-3,72,-4,83,-36,5,8,-97], [45,5,72,9,83,-24,5,-16,-97], [90,10,72,17,83,2,5,-31,-97], [135,9,72,15,83,26,5,-27,-97],
  [180,3,72,4,83,36,5,-8,-97], [225,-5,72,-9,83,24,5,16,-97], [270,-10,72,-17,83,-2,5,31,-97], [315,-9,72,-15,83,-26,5,27,-97],
  [0,-4,72,-5,82,-35,4,10,-90], [45,5,72,9,82,-27,4,-26,-90], [90,11,72,18,82,-3,4,-47,-90], [135,10,72,16,82,23,4,-40,-90],
  [180,4,72,5,82,35,4,-10,-90], [225,-5,72,-9,82,27,4,26,-90], [270,-11,72,-18,82,3,4,47,-90], [315,-10,72,-16,82,-23,4,40,-90],
  [0,-1,72,-2,82,-38,6,14,-75], [45,7,72,12,82,-23,6,-10,-75], [90,12,72,19,82,5,6,-29,-75], [135,9,72,15,82,31,6,-30,-75],
  [180,1,72,2,82,38,6,-14,-75], [225,-7,72,-12,82,23,6,10,-75], [270,-12,72,-19,82,-5,6,29,-75], [315,-9,72,-15,82,-31,6,30,-75],
  [0,2,72,2,83,-39,9,15,-85], [45,9,72,14,83,-10,9,22,-85], [90,10,72,18,83,25,9,16,-85], [135,6,72,11,83,45,9,0,-85],
  [180,-2,72,-2,83,39,9,-15,-85], [225,-9,72,-14,83,10,9,-22,-85], [270,-10,72,-18,83,-25,9,-16,-85], [315,-6,72,-11,83,-45,9,0,-85],
  [0,4,72,5,83,-36,16,13,-100], [45,9,72,15,83,4,16,34,-100], [90,10,72,17,83,42,16,34,-100], [135,4,72,9,83,56,16,14,-100],
  [180,-4,72,-5,83,36,16,-13,-100], [225,-9,72,-15,83,-4,16,-34,-100], [270,-10,72,-17,83,-42,16,-34,-100], [315,-4,72,-9,83,-56,16,-14,-100],
] as const;

function pixels(state: ReturnType<typeof createClipProjection>, joint: number): [number, number] {
  const rootX = state.positions[0]!; const rootY = state.positions[1]!;
  return [roundHalfAway((state.positions[joint * 3]! - rootX) * 128), roundHalfAway((state.positions[joint * 3 + 1]! - rootY) * 128)];
}

describe('clip projection', () => {
  it('matches Python golden samples within two pixels at 128 ppm', () => {
    const state = createClipProjection(walk); let worst = 0;
    for (let sample = 0; sample < golden.length; sample += 1) {
      const row = golden[sample]!; const frame = chosen[Math.floor(sample / 8)]!; resetClipProjection(state);
      projectClipFrame(walk, state, frame, row[0]);
      const actual = [...pixels(state, 2), ...pixels(state, 3), ...pixels(state, 10), ...pixels(state, 14)];
      actual.forEach((value, index) => { worst = Math.max(worst, Math.abs(value - row[index + 1]!)); });
    }
    expect(worst).toBeLessThanOrEqual(2);
  });

  it('clamps every limb shortening to 0.45 and reuses all output storage', () => {
    const state = createClipProjection(walk); const output = projectClipFrame(walk, state, 0, 0);
    const poses = output.poses; const affines = output.affines; let minimum = Infinity;
    for (const yaw of [0, 45, 90, 135, 180, 225, 270, 315]) for (let frame = 0; frame < walk.frameCount; frame += 1) {
      expect(projectClipFrame(walk, state, frame, yaw)).toBe(output);
      for (let part = 4; part < 16; part += 1) {
        const affine = poses[part]!.affine; const along = Math.hypot(affine[1]!, affine[4]!); const base = state.partMetrics[(state.currentViews[part]! * 16 + part) * 4 + 1]!;
        minimum = Math.min(minimum, along / base);
      }
    }
    expect(output.poses).toBe(poses); expect(output.affines).toBe(affines); expect(minimum).toBeGreaterThanOrEqual(.44999);
  });

  it('uses the target rig bone lengths instead of the source skeleton lengths', async () => {
    const shortRig = await loadRigSet({ ...createPlaceholderRigManifest('short'), heightM: .85 });
    const normal = createClipProjection(walk); const short = createClipProjection(walk, shortRig);
    projectClipFrame(walk, normal, 0, 0); projectClipFrame(walk, short, 0, 0);
    const normalTorso = Math.hypot(normal.positions[6]! - normal.positions[0]!, normal.positions[7]! - normal.positions[1]!);
    const shortTorso = Math.hypot(short.positions[6]! - short.positions[0]!, short.positions[7]! - short.positions[1]!);
    expect(shortTorso).toBeCloseTo(normalTorso * .5, 4); shortRig.dispose();
  });

  it('prefers an explicit target bone length over the height fallback', async () => {
    const rigSet = await loadRigSet({ ...createPlaceholderRigManifest('long_torso'), boneLengthsM: { torso: .8 } });
    const state = createClipProjection(walk, rigSet); projectClipFrame(walk, state, 0, 0);
    const torso = Math.hypot(state.positions[6]! - state.positions[0]!, state.positions[7]! - state.positions[1]!, state.positions[8]! - state.positions[2]!);
    expect(torso).toBeCloseTo(.8 * walk.lengthRatioU16[0]! / 32767, 5); rigSet.dispose();
  });

  it('swaps both direction and length tracks when mirroring limbs', () => {
    const ratios = walk.lengthRatioU16.slice(); ratios[4] = 16384; ratios[5] = 32767;
    const clip = { ...walk, lengthRatioU16: ratios }; const normal = createClipProjection(clip); const mirrored = createClipProjection(clip);
    projectClipFrame(clip, normal, 0, 0, false); projectClipFrame(clip, mirrored, 0, 0, true);
    const length = (state: typeof normal, start: number, end: number) => Math.hypot(
      state.positions[end * 3]! - state.positions[start * 3]!, state.positions[end * 3 + 1]! - state.positions[start * 3 + 1]!,
      state.positions[end * 3 + 2]! - state.positions[start * 3 + 2]!,
    );
    expect(length(mirrored, 4, 5)).toBeCloseTo(length(normal, 8, 9), 5);
    expect(length(mirrored, 8, 9)).toBeCloseTo(length(normal, 4, 5), 5);
  });

  it('applies ten-degree hysteresis around a view boundary', () => {
    const state = createClipProjection(walk); projectClipFrame(walk, state, 0, 0);
    const initial = state.currentViews[2]; projectClipFrame(walk, state, 0, 8);
    expect(state.currentViews[2]).toBe(initial); resetClipProjection(state); projectClipFrame(walk, state, 0, 120);
    expect(state.currentViews[2]).not.toBe(initial);
  });

  it('shares an exact projection and invalidates it across yaw changes', () => {
    const clip = { ...walk };
    const first = createClipProjection(clip); const second = createClipProjection(clip);
    const sin = vi.spyOn(Math, 'sin'); projectClipFrame(clip, first, 7, 0); sin.mockClear();
    projectClipFrame(clip, second, 7, 0);
    expect(sin).not.toHaveBeenCalled();
    expect(Array.from(second.output.affines)).toEqual(Array.from(first.output.affines));
    projectClipFrame(clip, second, 7, 45); expect(sin).toHaveBeenCalled();
    expect(Array.from(second.output.affines)).not.toEqual(Array.from(first.output.affines));
  });

  it('does not share cached projections between clips', () => {
    const firstClip = { ...walk }; const secondClip = { ...sword };
    const first = createClipProjection(firstClip); const second = createClipProjection(secondClip);
    const sin = vi.spyOn(Math, 'sin'); projectClipFrame(firstClip, first, 0, 0); sin.mockClear();
    projectClipFrame(secondClip, second, 0, 0); expect(sin).toHaveBeenCalled();
    expect(Array.from(second.output.affines)).not.toEqual(Array.from(first.output.affines));
  });

  it('keeps incoming hysteresis history in the cache key', () => {
    const clip = { ...walk }; const fromLeft = createClipProjection(clip); const fromRight = createClipProjection(clip);
    projectClipFrame(clip, fromLeft, 14, -45); projectClipFrame(clip, fromRight, 14, 45);
    projectClipFrame(clip, fromLeft, 14, 0); const leftViews = Array.from(fromLeft.currentViews);
    const sin = vi.spyOn(Math, 'sin'); projectClipFrame(clip, fromRight, 14, 0);
    expect(sin).toHaveBeenCalled(); expect(Array.from(fromRight.currentViews)).not.toEqual(leftViews);
  });

  it('matches the Python Q4 torso-view switch counts in all eight directions', () => {
    const state = createClipProjection(walk); const switches: number[] = [];
    for (const yaw of [0, 45, 90, 135, 180, 225, 270, 315]) {
      resetClipProjection(state); let previous = -1; let count = 0;
      for (let frame = 0; frame < walk.frameCount; frame += 1) {
        projectClipFrame(walk, state, frame, yaw); const current = state.currentViews[2]!;
        if (previous >= 0 && current !== previous) count += 1;
        previous = current;
      }
      switches.push(count);
    }
    expect(switches).toEqual([2, 0, 0, 0, 2, 0, 0, 0]);
  });

  it('matches sword Q4 switching and Q6 integer projection limits', () => {
    const state = createClipProjection(sword); const switches: number[] = [];
    let maxAxisDeviation = 0; let maxGripError = 0;
    for (const yaw of [0, 45, 90, 135, 180, 225, 270, 315]) {
      resetClipProjection(state); let previous = -1; let count = 0;
      for (let frame = 0; frame < sword.frameCount; frame += 1) {
        const output = projectClipFrame(sword, state, frame, yaw); const current = state.currentViews[2]!;
        if (previous >= 0 && current !== previous) count += 1; previous = current;
        const axisX = -output.weaponAffine[1]!; const axisY = output.weaponAffine[4]!;
        const axisLength = Math.max(Math.hypot(axisX, axisY), 1e-12);
        const px = roundHalfAway(axisX * 128); const py = roundHalfAway(axisY * 128);
        const pixelLength = Math.max(Math.hypot(px, py), 1e-12);
        const cosine = Math.min(1, Math.max(-1, (axisX * px + axisY * py) / axisLength / pixelLength));
        maxAxisDeviation = Math.max(maxAxisDeviation, Math.acos(cosine) * 180 / Math.PI);
        const grip = sword.weaponHand === 'L' ? 7 : 11; const gx = (state.positions[grip * 3]! - state.positions[0]!) * 128;
        const gy = (state.positions[grip * 3 + 1]! - state.positions[1]!) * 128;
        maxGripError = Math.max(maxGripError, Math.hypot(roundHalfAway(gx) - gx, roundHalfAway(gy) - gy));
      }
      switches.push(count);
    }
    expect(switches).toEqual([6, 5, 6, 6, 6, 5, 6, 6]);
    expect(maxAxisDeviation).toBeCloseTo(.485, 2); expect(maxGripError).toBeCloseTo(.695, 2);
  });
});
