from pathlib import Path
import copy, json, hashlib, shutil, yaml
from datetime import datetime
from zoneinfo import ZoneInfo
from PIL import Image

ROOT=Path(__file__).resolve().parents[2]
entries={e['id']:e for e in yaml.safe_load((ROOT/'manifest.yaml').read_text())}
for typ,c in [('yamen',2),('biaoju',2),('temple_hall',1)]:
    d=ROOT/'revisions_r3'/typ; result=json.loads((d/'result.json').read_text()); aid=result['id']; r=result['candidate_records'][c-1]; e=copy.deepcopy(entries[aid]); old=yaml.safe_load((ROOT/e['metadata']).read_text()); src=d/f'candidate_{c}.png'; final=ROOT/e['file']; shutil.copyfile(final,d/'original_before_r3.png')
    im=Image.open(src); box=im.getchannel('A').point(lambda x:255 if x>=3 else 0).getbbox(); box=[max(0,box[0]-4),max(0,box[1]-4),min(im.width,box[2]+4),min(im.height,box[3]+4)]; cut=im.crop(box)
    w,h=result['footprint']; L,F,R=r['ground_lfr_source_px']; scale=32*(w+h)/(R[0]-L[0]); resized=[round(cut.width*scale),round(cut.height*scale)]; sprite=cut.resize(resized,Image.Resampling.LANCZOS); out=Image.new('RGBA',(resized[0]+32,resized[1]+32)); out.paste(sprite,(16,16)); out.save(final)
    sx,sy=resized[0]/cut.width,resized[1]/cut.height; trans=lambda p:[round((p[0]-box[0])*sx+16,3),round((p[1]-box[1])*sy+16,3)]; anchor=trans(r['source_anchor_px']); fp=[trans(p) for p in [L,F,R]]; sha=hashlib.sha256(final.read_bytes()).hexdigest()
    alpha=out.getchannel('A'); hist=alpha.histogram(); bbox=alpha.getbbox(); verification={'mode':out.mode,'alpha_extrema':list(alpha.getextrema()),'zero_alpha_pixels':hist[0],'partial_alpha_pixels':sum(hist[1:255]),'opaque_pixels':hist[255],'nonzero_alpha_bbox':list(bbox),'margins_px':[bbox[0],bbox[1],out.width-bbox[2],out.height-bbox[3]],'source_viewed':True,'final_viewed':False,'runtime_assembly_tested':False}
    processing={'source_file':str(src.relative_to(ROOT)),'source_path':r['source_path'],'source_sha256':r['sha256'],'source_size_px':list(im.size),'crop_box':box,'crop_rule':'alpha>=3 bbox expanded4 source px; retained alpha unmodified','requested_uniform_scale':scale,'rounded_effective_scale_xy':[sx,sy],'resized_px':resized,'canvas_px':list(out.size),'paste_offset_px':[16,16],'final_sha256':sha}
    measurement={'method':result['measurement_method'],'uncertainty_source_px':4,'ground_lfr_source_px':[L,F,R],'ground_lfr_final_px':fp,'ground_center_source_px':r['source_anchor_px'],'source_slopes':r['slopes'],'source_edge_fits':r['edge_fits'],'slope_abs_errors':[abs(abs(x)-.5) for x in r['slopes']],'slope_tolerance_suggestion':.03,'slope_check':r['axis_pass'],'observed_w_h_ratio':r['horizontal_ratio'],'target_w_h_ratio':w/h,'relative_ratio_error':r['relative_ratio_error'],'ratio_check':r['ratio_pass'],'width_scale_target_px':32*(w+h),'width_scale_actual_px':fp[2][0]-fp[0][0],'depth_scale_target_px':16*(w+h),'depth_observed_px':2*fp[1][1]-fp[0][1]-fp[2][1]}
    note='第3轮2选1改善候选；双轴或占地比残差仍未通过，selected不等于passed；仍为candidate。仅透明裁切、等比Lanczos重采样与16px透明pad。'
    meta=copy.deepcopy(old); meta.update(anchor_px=anchor,measurement=measurement,processing=processing,verification=verification,candidate_count=2,selected_candidate=c,selection_note=note,previous_metadata=e['metadata'],revision=3); meta['projection_contract']['geometry_release_ready']=False; meta['projection_contract']['geometry_verified']=False; meta['limitations'][1]='已改善但未解决：双轴/占地比未同时通过；详见本轮measurement及result.json，不能声称精确2:1拼接已验收'
    (d/'meta.yaml').write_text(json.dumps(meta,ensure_ascii=False,separators=(',',':'))+'\n')
    guide='guide.png' if typ=='yamen' else ('guide_compensated_2.png' if typ=='biaoju' else '../../revisions_r2/temple_hall/candidate_2.png'); reference=str((d/guide).resolve())
    e.update(prompt=r['prompt'],references=[reference],created=datetime.now(ZoneInfo('America/Los_Angeles')).isoformat(timespec='seconds'),source_path=r['source_path'],size=f'{out.width}x{out.height}',sha256=sha,status='candidate',notes=note,metadata=str((d/'meta.yaml').relative_to(ROOT)),source_sha256=r['sha256'],candidate_count=2);e['building']['anchor']=anchor;e['projection_contract']['geometry_release_ready']=False;e['projection_contract']['geometry_verified']=False;e['style_reference_chain'].append({'path':reference,'role':'第3轮实际image_gen输入；只提供几何/既有建筑修复参考，按实测记录保留残差'})
    r.update(selected=True,selected_for_improvement=True,rejection_reason=None,acceptance_note=note);result.update(selected_candidate=c,selected_for_improvement=True,geometry_release_ready=False,geometry_pass=False,original_unchanged=False,manifest_replacement=e,final_sha256=sha,final_size=list(out.size),final_anchor=anchor,processing=processing,result='FAIL：改善候选已替换，未通过严格几何验收')
    (d/'result.json').write_text(json.dumps(result,ensure_ascii=False,separators=(',',':'))+'\n'); print(typ,c,e['size'],sha,'source',r['sha256'],'anchor',anchor)
